POST https://node-server-pq93.onrender.com/videos
Content-Type: application/json

{
  "title": "Video01 node",
  "description": "Esse é o primeiro vídeo",
  "duration": 180
}

###

GET  https://node-server-pq93.onrender.com/videos

###

PUT https://node-server-pq93.onrender.com/videos/1b4abbfa-08ac-42be-941c-2f312d41870a
Content-Type: application/json

{
  "title": "Video02",
  "description": "Esse é o primeiro vídeo",
  "duration": 180
}

###

DELETE https://node-server-pq93.onrender.com/videos/1b4abbfa-08ac-42be-941c-2f312d41870a